### ISSUE TITLE
Add compilation command to readme

### ISSUE THREAD

**Issue by rwegener2** [Ocean-Dynamics-Group/GroupExpectations#1]
## Goal
Document how to generate updated versions of the document

## Notes
I was thinking it would be nice to add a sentence or two describing how to create a new pdf, although I'm not actually sure how to do that outside of overleaf. How do other folks usually generate a pdf from the .tex? cc @tomchor @igoruchoa  

Googling how to do that turns up:
* a command line tool `pdflatex`
* downloading a gui and using that

**Comment by igoruchoa** [comment]
Overleaf is my default way of dealing with .tex, but I used to use TexStudio for large compilations (files) since sometimes overleaf cannot handle them. I think that falls into the gui option. We can also just compile and generate pdf files through terminal which I think is the way @tomchor does it, if I remember correctly.

**Comment by tomchor** [comment]
> Overleaf is my default way of dealing with .tex, but I used to use TexStudio for large compilations (files) since sometimes overleaf cannot handle them. I think that falls into the gui option. We can also just compile and generate pdf files through terminal which I think is the way @tomchor does it, if I remember correctly.

Yup, I only use the terminal (either `pdflatex` or `xelatex`), but that are many many ways of doing it. 

Perhaps a couple of links in the `README` that explain different ways of compiling a document can be more helpful than prescribing one single method of doing it.

**Comment by tomchor** [comment]
This is just for testing (so ignore this message), but I wonder what happens if I link the @Ocean-Dynamics-Group handle...

**Comment by reint-fischer** [comment]
Is there a reason you don't (want to) use overleaf?

**Comment by wenegrat** [comment]
I'm a fan of overleaf for collaborative writing, so maybe that would be a better platform for this?

I guess my thought is that the 'writing' part of this might be small relative to the 'discussion' part, ie. what do we want to change and why, so perhaps github would work better? I'm not familiar enough to really answer that.

**Comment by tomchor** [comment]
> Is there a reason you don't (want to) use overleaf?

Sorry @reint-fischer I just realized that I've never answered you!

Basically it's just a personal preference. Overleaf makes it really easy to write documents together, and makes things really user-friendly and pretty, but (imo) that comes at some cost. For me most important things are

- I'm much more efficient writing using `vim` (because it's an _extremely_ powerful editor) than their built-in editor
- Their panels (including the pdf live view) take a lot of visual space. I'm a fan of small screens (I use a 13'' laptop) so that means screen space is at a premium!
- The panels and the fact that you use in a browser makes it pretty distracting. When I'm writing I use `vim` in full screen mode so the only thing I'm looking at is text on a black screen. That allows me to focus _only_ on the content when writing which I think is pretty powerful and makes me much more productive

But again, that's just my personal preference :)
